project:
  type: website

website:
  title: "Designing the Data Science Classroom"
  description: "Homepage for rstudio::conf(2022) workshop"
  sidebar:
    background: "#2e3846"
    logo: "images/logo.gif"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/matackett/ecots2022-modern-regression
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/249609
        text: RStudio Cloud
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: modules.qmd
       text: Modules
     - href: resources.qmd
       text: Resources
     - href: license.qmd
       text: License

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

editor: visual

