project:
  type: website
  resources:
    - "images/twitter-card.png"

website:
  page-navigation: true
  title: "Designing the Data Science Classroom"
  description: "Homepage for rstudio::conf(2022) workshop"
  site-url: "https://rstudio-conf-2022.github.io/teach-ds/"
  
  repo-url: https://github.com/rstudio-conf-2022/teach-ds
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@minebocek"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Mine Çetinkaya-Rundel and Maria Tackett"
    background: "#2e3846"

  sidebar:
    background: "#2e3846"
    logo: "images/logo.gif"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rstudio-conf-2022/teach-ds
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/249609
        text: RStudio Cloud
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: schedule.qmd
     - href: resources.qmd
     - href: license.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

editor: visual

